### ISSUE TITLE
New Icon And Google Play Feature Graphic

### ISSUE THREAD

**Issue by DavidXochipilli** [dmitriy1morozov/Chinese_Checkers#2]
Are you interested in a new launcher icon and [Google Play](https://play.google.com/store/apps/details?id=borsh.diploma_chinese_checkers) feature graphic?

**Comment by DavidXochipilli** [comment]
The icon is under the CC0 1.0 Universal license.
[Halma.zip](https://github.com/dmitriy1morozov/Chinese_Checkers/files/1424391/Halma.zip)

**Comment by dmitriy1morozov** [comment]
Nice icon. I will consider updating the original icon and replace it with your proposal.

**Comment by dmitriy1morozov** [comment]
Icon launcher updated. David, thank you for the contribution!

**Comment by VickieSullivan** [comment]
Is this update already on [Google Play](https://play.google.com/store/apps/details?id=borsh.diploma_chinese_checkers)?
By the way, can you please upload the .apk [on GitHub too please](https://github.com/dmitriy1morozov/Chinese_Checkers/releases)?

**Comment by dmitriy1morozov** [comment]
Google play hasn't been updated. APK builds are not pushed to git so I didn't upload it here too. This project is kinda legacy and there is much work required to do in order to update it to the nowadays best practices. If you are interested in a new APK you may easily download the source code and build the project in AS.
